export const QUERY_KEYS = {
  // Board
  GET_BOARD_LIST: 'GET_BOARD_LIST',

  // Task
  GET_TASK_LIST: 'GET_TASK_LIST',

  // Group
  GET_GROUP_LIST: 'GET_GROUP_LIST',

  // User
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
  GET_ALL_USERS: 'GET_ALL_USERS',

  // Access
  GET_ACCESS_LIST: 'GET_ACCESS_LIST',
  GET_PERMISSION: 'GET_PERMISSION',
};

export const MUTATION_KEYS = {
  // Board
  CREATE_BOARD: 'CREATE_BOARD',
  UPDATE_BOARD: 'UPDATE_BOARD',
  DELETE_BOARD: 'DELETE_BOARD',

  // Task
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASK_BY_GROUPID: 'DELETE_TASK_BY_GROUPID',
  REORDER_TASK: 'REORDER_TASK',

  // Group
  CREATE_GROUP: 'CREATE_GROUP',
  UPDATE_GROUP: 'UPDATE_GROUP',
  DELETE_GROUP: 'DELETE_GROUP',
  REORDER_GROUP: 'REORDER_GROUP',

  // Access
  CHANGE_OWNER: 'CHANGE_OWNER',
  DELETE_ACCESS: 'DELETE_ACCESS',
  SHARE_ACCESS: 'SHARE_ACCESS',
  UPDATE_ACCESS: 'UPDATE_ACCESS',

  // File
  UPLOAD: 'UPLOAD',
};
