export const QUERY_KEYS = {
  // Board
  GET_BOARD_LIST: 'GET_BOARD_LIST',

  // Task
  GET_TASK_LIST: 'GET_TASK_LIST',

  // Group
  GET_GROUP_LIST: 'GET_GROUP_LIST',

  // User
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
  GET_ALL_USERS: 'GET_ALL_USERS',
};

export const MUTATION_KEYS = {
  // Board
  CREATE_BOARD: 'CREATE_BOARD',
  UPDATE_BOARD: 'UPDATE_BOARD',
  DELETE_BOARD: 'DELETE_BOARD',

  // Task
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASK_BY_GROUPID: 'DELETE_TASK_BY_GROUPID',

  // Group
  CREATE_GROUP: 'CREATE_GROUP',
  UPDATE_GROUP: 'UPDATE_GROUP',
  DELETE_GROUP: 'DELETE_GROUP',
  REORDER_GROUP: 'REORDER_GROUP',

  // User
};
