export const QUERY_KEYS = {
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_BOARD_LIST: 'GET_BOARD_LIST',
  GET_TASK_LIST: 'GET_TASK_LIST',
};
